name: GitHub Actions Demo
run-name: ${{github.actor}} is testing out Github Actions
on: [push]
jobs:
  hellow-world-job:
    runs-on: ubuntu-latest
    steps: 
    - name: Hello World
      run: echo "Hello Millionaire"
